// <auto-generated />
using System;
using HAHN.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAHN.Infrastructure.Migrations
{
    [DbContext(typeof(HahnDbContext))]
    [Migration("20241018012039_initial seed")]
    partial class initialseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAHN.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"), 1000L);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = 1002,
                            Date = new DateTime(2022, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Promotion code issued",
                            Status = 1
                        },
                        new
                        {
                            TicketId = 1003,
                            Date = new DateTime(2022, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Additional user account",
                            Status = 1
                        },
                        new
                        {
                            TicketId = 1004,
                            Date = new DateTime(2022, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Change payment method",
                            Status = 1
                        },
                        new
                        {
                            TicketId = 1005,
                            Date = new DateTime(2022, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Activate account",
                            Status = 0
                        },
                        new
                        {
                            TicketId = 1007,
                            Date = new DateTime(2022, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Great job",
                            Status = 0
                        },
                        new
                        {
                            TicketId = 1008,
                            Date = new DateTime(2022, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Another Great Job",
                            Status = 0
                        },
                        new
                        {
                            TicketId = 1000,
                            Date = new DateTime(2022, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Help with Login",
                            Status = 0
                        },
                        new
                        {
                            TicketId = 1024,
                            Date = new DateTime(2022, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Happy Customer",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
